2024-08-17 02:11:24.451 WARNING (Recorder) [homeassistant.components.recorder.util] The system could not validate that the sqlite3 database at //config/home-assistant_v2.db was shutdown cleanly
2024-08-17 02:11:24.478 WARNING (Recorder) [homeassistant.components.recorder.util] Ended unfinished session (id=14 from 2024-08-16 06:51:13.811961)
2024-08-17 02:11:27.328 ERROR (MainThread) [homeassistant.components.mqtt.client] Failed to connect to MQTT server due to exception: [Errno 111] Connection refused
2024-08-17 04:23:55.277 WARNING (MainThread) [aioesphomeapi.connection] my_first_esphome @ 192.168.1.11: Connection error occurred: my_first_esphome @ 192.168.1.11: EOF received
2024-08-17 04:24:11.534 WARNING (MainThread) [aioesphomeapi.connection] my_first_esphome @ 192.168.1.11: Connection error occurred: my_first_esphome @ 192.168.1.11: EOF received
2024-08-17 04:24:11.543 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for my_first_esphome @ 192.168.1.11: Error connecting to [AddrInfo(family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, proto=6, sockaddr=IPv4Sockaddr(address='192.168.1.11', port=6053))]: [Errno 111] Connect call failed ('192.168.1.11', 6053) (SocketAPIError)
2024-08-17 04:26:31.836 WARNING (MainThread) [aioesphomeapi.connection] my_first_esphome @ 192.168.1.11: Connection error occurred: my_first_esphome @ 192.168.1.11: EOF received
2024-08-17 04:26:31.837 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for my_first_esphome @ 192.168.1.11: Error connecting to [AddrInfo(family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, proto=6, sockaddr=IPv4Sockaddr(address='192.168.1.11', port=6053))]: [Errno 111] Connect call failed ('192.168.1.11', 6053) (SocketAPIError)
